version: "2.4"
services:
   pev-simulator:
    build:
      context: ./
      args:
         UID: 1000
         GID: 1000
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./:/mnt
    image: pev-simulator:latest
    networks:
      app_net:
        ipv4_address: 10.0.0.2
        ipv6_address: 2001:3984:3989::10
    container_name:  pev-simulator

networks:
  app_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
        - subnet: "2001:3984:3989::/64"
